name: 'Add Binder link'
description: 'Add Binder link to all notebooks of a repository'
author: 'Quentin Fortier <qpfortier@gmail.com>'
inputs:
  env:
    description: 'GitHub repo defining the Binder environment (must have nbgitpuller)'
    required: false
    default: 'fortierq/itc-binder' # example
  branch-env:
    description: 'Branch of the Binder environment'
    required: false
    default: 'main'
  force:
    description: 'Force the generation of every link (even if a link was already present)'
    required: false
    default: 'false'
  
runs:
  using: 'composite'
  steps:
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
      
    - name: Add link
      shell: bash
      run: |
        for file in $(find . -name '*.ipynb'); do
          python3 ${{ github.action_path }}/add_binder_link.py ${{ github.repository }} ${file##./} ${{ inputs.env }} ${GITHUB_REF##*/} ${{ inputs.branch-env }} ${{ inputs.force }}
        done

    - name: Push
      shell: bash
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
        git add .
        git commit -m 'Add Binder link' || true
        git push || true
